# Generated by Django 4.1.7 on 2023-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=125)),
                ('Category', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=255)),
                ('Rating', models.FloatField()),
                ('Image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
